services:
  c2:
    image: c2-server:latest
    build:
      context: ../../.
      dockerfile: Dockerfile
    ports:
      - "13406:13405"
    networks:
      - shared-network

  java-agent:
    build:
      context: .
      dockerfile: agent-java.dockerfile
    networks:
      - shared-network

  cpp-agent:
    build:
      context: .
      dockerfile: agent-cpp.dockerfile
    ports:
      - "9937:9936"
    networks:
      - shared-network

  cpp-agent-fast-compact:
    build:
      context: .
      dockerfile: agent-cpp_fast_compact.dockerfile
    ports:
      - "9938:9936"
    networks:
      - shared-network

  prometheus:
    build:
      context: .
      dockerfile: prometheus.dockerfile
    ports:
      - "13407:9090"
    networks:
      - shared-network

networks:
  shared-network:
